# Generated by Django 2.2.3 on 2019-08-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='酒店名')),
                ('nowman', models.CharField(blank=True, max_length=3, null=True, verbose_name='入住率')),
            ],
        ),
        migrations.CreateModel(
            name='hotelinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('hotel_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='酒店名')),
                ('location', models.CharField(max_length=50, null=True, verbose_name='酒店位置')),
                ('pinfen', models.CharField(max_length=50, verbose_name='评分')),
                ('customer', models.CharField(blank=True, max_length=50, null=True, verbose_name='消费水平')),
                ('price', models.CharField(max_length=10, verbose_name='均价')),
                ('images', models.CharField(max_length=50, verbose_name='酒店图片')),
                ('city', models.CharField(max_length=50, verbose_name='城市名')),
                ('boss_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='商家名')),
            ],
        ),
    ]
