# Generated by Django 2.2.3 on 2019-08-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinfo',
            name='images',
            field=models.CharField(max_length=200, verbose_name='酒店图片'),
        ),
    ]
