# Generated by Django 2.2.3 on 2019-08-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelinfo', '0002_auto_20190822_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinfo',
            name='location',
            field=models.CharField(max_length=200, null=True, verbose_name='酒店位置'),
        ),
    ]
