# Generated by Django 2.2.3 on 2019-08-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelinfo', '0003_auto_20190822_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='left_home',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='剩余房间数量'),
        ),
    ]
