# Generated by Django 2.2.3 on 2019-08-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelinfo', '0004_hotelinfo_left_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinfo',
            name='boss_name',
            field=models.CharField(blank=True, default='0', max_length=50, null=True, verbose_name='商家名'),
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='left_home',
            field=models.CharField(blank=True, default='0', max_length=50, null=True, verbose_name='剩余房间数量'),
        ),
    ]
