# Generated by Django 2.2.3 on 2019-08-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelinfo', '0005_auto_20190822_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelinfo',
            name='boss_name',
        ),
        migrations.RemoveField(
            model_name='hotelinfo',
            name='left_home',
        ),
    ]
