# Generated by Django 2.2.3 on 2019-08-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelinfo', '0007_auto_20190822_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelinfo',
            name='boss_name',
        ),
    ]
