# Generated by Django 2.2.3 on 2019-08-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelinfo', '0008_remove_hotelinfo_boss_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelinfo',
            options={'verbose_name': '酒店信息', 'verbose_name_plural': '酒店信息'},
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='left_home',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='剩余房间数量'),
        ),
    ]
