# Generated by Django 2.2.3 on 2019-08-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='good',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50, verbose_name='用户标志')),
                ('article_id', models.CharField(max_length=50, verbose_name='文章标识')),
                ('is_good', models.CharField(max_length=1, verbose_name='是否点赞标志')),
            ],
        ),
        migrations.CreateModel(
            name='submmit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('author', models.CharField(max_length=50)),
                ('time', models.DateField(blank=True, null=True, verbose_name='提交时间')),
                ('touxiang', models.CharField(max_length=500, verbose_name='头像地址')),
                ('gooded', models.IntegerField(default=0, null=True, verbose_name='被点赞数')),
                ('is_pass', models.CharField(default=0, max_length=1, verbose_name='是否审核通过')),
                ('waitselect', models.CharField(default=0, max_length=1, verbose_name='是否审核过')),
            ],
        ),
    ]
