# Generated by Django 2.2.3 on 2019-08-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_keep',
            field=models.CharField(default=0, max_length=1, verbose_name='是否收藏的标志'),
        ),
        migrations.AlterField(
            model_name='good',
            name='is_good',
            field=models.CharField(default=0, max_length=1, verbose_name='是否点赞标志'),
        ),
    ]
