# Generated by Django 2.2.3 on 2019-08-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20190808_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submmit',
            old_name='id',
            new_name='article_id',
        ),
        migrations.RenameField(
            model_name='submmit',
            old_name='author',
            new_name='author_id',
        ),
    ]
