# Generated by Django 2.2.3 on 2019-08-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_auto_20190808_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='user_id',
            new_name='author_id',
        ),
    ]
