# Generated by Django 2.2.3 on 2019-08-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_auto_20190808_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='submmit',
            name='author_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
