# Generated by Django 2.2.3 on 2019-08-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_submmit_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submmit',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='城市名'),
        ),
    ]
