# Generated by Django 2.2.3 on 2019-08-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0009_submmit_requests_math'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submmit',
            name='requests_math',
            field=models.IntegerField(default=0, null=True, verbose_name='访问量'),
        ),
    ]
