# Generated by Django 2.2.3 on 2019-07-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scenic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('imgpath', models.CharField(blank=True, max_length=200, null=True, verbose_name='食物照片')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='景点名')),
                ('star', models.CharField(max_length=50, null=True, verbose_name='星级')),
                ('commet', models.CharField(max_length=50, verbose_name='评分')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='距离')),
                ('labels', models.CharField(max_length=10, verbose_name='标签')),
                ('prices', models.CharField(max_length=50, verbose_name='价格')),
                ('merit', models.CharField(max_length=50, verbose_name='优惠券')),
                ('visit_pro', models.CharField(max_length=50, verbose_name='亮点')),
            ],
        ),
    ]
