# Generated by Django 2.2.3 on 2019-07-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户名')),
                ('images', models.CharField(blank=True, max_length=50, null=True, verbose_name='头像地址')),
                ('location', models.CharField(blank=True, max_length=15, null=True, verbose_name='地址')),
                ('openid', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户唯一标识')),
            ],
        ),
    ]
