# Generated by Django 2.2.3 on 2019-07-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='images',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='头像地址'),
        ),
    ]
