# Generated by Django 2.2.3 on 2019-08-14 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinfo_is_starff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
    ]
