# Generated by Django 2.2.3 on 2019-08-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_age',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('step1', models.CharField(blank=True, max_length=10, null=True, verbose_name='15-25岁')),
                ('step2', models.CharField(blank=True, max_length=10, null=True, verbose_name='25-35岁')),
                ('step3', models.CharField(blank=True, max_length=10, null=True, verbose_name='35-45岁')),
                ('step4', models.CharField(blank=True, max_length=10, null=True, verbose_name='45-60岁')),
                ('step5', models.CharField(blank=True, max_length=10, null=True, verbose_name='60岁以上')),
                ('city', models.CharField(max_length=15, null=True, verbose_name='城市名')),
            ],
        ),
        migrations.CreateModel(
            name='customer_from',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='目标城市')),
                ('value', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='customer_method',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('lvxingshe', models.CharField(blank=True, max_length=10, null=True, verbose_name='旅行社')),
                ('mafengwo', models.CharField(blank=True, max_length=10, null=True, verbose_name='马蜂窝')),
                ('xiecheng', models.CharField(blank=True, max_length=10, null=True, verbose_name='携程')),
                ('meituan', models.CharField(blank=True, max_length=10, null=True, verbose_name='美团')),
                ('tuniu', models.CharField(blank=True, max_length=10, null=True, verbose_name='途牛')),
                ('city', models.CharField(max_length=15, null=True, verbose_name='城市名')),
            ],
        ),
        migrations.CreateModel(
            name='customer_staytime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('step1_short', models.CharField(blank=True, max_length=10, null=True, verbose_name='15-25岁的最短停留时间')),
                ('step2_short', models.CharField(blank=True, max_length=10, null=True, verbose_name='25-35岁的最短停留时间')),
                ('step3_short', models.CharField(blank=True, max_length=10, null=True, verbose_name='35-45岁的最短停留时间')),
                ('step4_short', models.CharField(blank=True, max_length=10, null=True, verbose_name='45-60岁的最短停留时间')),
                ('step5_short', models.CharField(blank=True, max_length=10, null=True, verbose_name='60岁以上的最短停留时间')),
                ('step1_long', models.CharField(blank=True, max_length=10, null=True, verbose_name='15-25岁的最长停留时间')),
                ('step2_long', models.CharField(blank=True, max_length=10, null=True, verbose_name='25-35岁的最长停留时间')),
                ('step3_long', models.CharField(blank=True, max_length=10, null=True, verbose_name='35-45岁的最长停留时间')),
                ('step4_long', models.CharField(blank=True, max_length=10, null=True, verbose_name='45-60岁的最长停留时间')),
                ('step5_long', models.CharField(blank=True, max_length=10, null=True, verbose_name='60岁以上的最长停留时间')),
                ('city', models.CharField(max_length=15, null=True, verbose_name='城市名')),
            ],
        ),
        migrations.CreateModel(
            name='customer_team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('step1', models.CharField(blank=True, max_length=10, null=True, verbose_name='2千元以上')),
                ('step2', models.CharField(blank=True, max_length=10, null=True, verbose_name='3千元以上')),
                ('step3', models.CharField(blank=True, max_length=10, null=True, verbose_name='4千元以上')),
                ('step4', models.CharField(blank=True, max_length=10, null=True, verbose_name='5千元以上')),
                ('step5', models.CharField(blank=True, max_length=10, null=True, verbose_name='6千元以上')),
                ('city', models.CharField(max_length=15, null=True, verbose_name='城市名')),
            ],
        ),
        migrations.CreateModel(
            name='customer_tools',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('ditie', models.CharField(blank=True, max_length=10, null=True, verbose_name='地铁')),
                ('gongjiao', models.CharField(blank=True, max_length=10, null=True, verbose_name='公交')),
                ('tubu', models.CharField(blank=True, max_length=10, null=True, verbose_name='徒步')),
                ('zijia', models.CharField(blank=True, max_length=10, null=True, verbose_name='自驾')),
                ('qixing', models.CharField(blank=True, max_length=10, null=True, verbose_name='骑行')),
                ('city', models.CharField(max_length=15, null=True, verbose_name='城市名')),
            ],
        ),
    ]
