# Generated by Django 2.2.3 on 2019-08-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_from',
            old_name='city',
            new_name='name',
        ),
    ]
