# Generated by Django 2.2.3 on 2019-08-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0002_auto_20190807_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_age',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer_age',
            name='step1',
        ),
        migrations.RemoveField(
            model_name='customer_age',
            name='step2',
        ),
        migrations.RemoveField(
            model_name='customer_age',
            name='step3',
        ),
        migrations.RemoveField(
            model_name='customer_age',
            name='step4',
        ),
        migrations.RemoveField(
            model_name='customer_age',
            name='step5',
        ),
        migrations.RemoveField(
            model_name='customer_method',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer_method',
            name='lvxingshe',
        ),
        migrations.RemoveField(
            model_name='customer_method',
            name='mafengwo',
        ),
        migrations.RemoveField(
            model_name='customer_method',
            name='meituan',
        ),
        migrations.RemoveField(
            model_name='customer_method',
            name='tuniu',
        ),
        migrations.RemoveField(
            model_name='customer_method',
            name='xiecheng',
        ),
        migrations.RemoveField(
            model_name='customer_staytime',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer_staytime',
            name='step1_long',
        ),
        migrations.RemoveField(
            model_name='customer_staytime',
            name='step1_short',
        ),
        migrations.RemoveField(
            model_name='customer_staytime',
            name='step2_long',
        ),
        migrations.RemoveField(
            model_name='customer_staytime',
            name='step2_short',
        ),
        migrations.RemoveField(
            model_name='customer_staytime',
            name='step3_long',
        ),
        migrations.RemoveField(
            model_name='customer_staytime',
            name='step3_short',
        ),
        migrations.RemoveField(
            model_name='customer_staytime',
            name='step4_long',
        ),
        migrations.RemoveField(
            model_name='customer_staytime',
            name='step4_short',
        ),
        migrations.RemoveField(
            model_name='customer_staytime',
            name='step5_long',
        ),
        migrations.RemoveField(
            model_name='customer_staytime',
            name='step5_short',
        ),
        migrations.RemoveField(
            model_name='customer_team',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer_team',
            name='step1',
        ),
        migrations.RemoveField(
            model_name='customer_team',
            name='step2',
        ),
        migrations.RemoveField(
            model_name='customer_team',
            name='step3',
        ),
        migrations.RemoveField(
            model_name='customer_team',
            name='step4',
        ),
        migrations.RemoveField(
            model_name='customer_team',
            name='step5',
        ),
        migrations.RemoveField(
            model_name='customer_tools',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer_tools',
            name='ditie',
        ),
        migrations.RemoveField(
            model_name='customer_tools',
            name='gongjiao',
        ),
        migrations.RemoveField(
            model_name='customer_tools',
            name='qixing',
        ),
        migrations.RemoveField(
            model_name='customer_tools',
            name='tubu',
        ),
        migrations.RemoveField(
            model_name='customer_tools',
            name='zijia',
        ),
        migrations.AddField(
            model_name='customer_age',
            name='location',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customer_age',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='目标城市'),
        ),
        migrations.AddField(
            model_name='customer_age',
            name='value',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer_method',
            name='location',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customer_method',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='目标城市'),
        ),
        migrations.AddField(
            model_name='customer_method',
            name='value',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer_staytime',
            name='location',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customer_staytime',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='目标城市'),
        ),
        migrations.AddField(
            model_name='customer_staytime',
            name='value',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer_team',
            name='location',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customer_team',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='目标城市'),
        ),
        migrations.AddField(
            model_name='customer_team',
            name='value',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer_tools',
            name='location',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customer_tools',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='目标城市'),
        ),
        migrations.AddField(
            model_name='customer_tools',
            name='value',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
