# Generated by Django 2.2.3 on 2019-08-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0003_auto_20190807_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_staytime',
            old_name='value',
            new_name='value_1',
        ),
        migrations.AddField(
            model_name='customer_staytime',
            name='value_2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
