# Generated by Django 2.2.3 on 2019-08-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='everycomponent',
            name='content',
            field=models.CharField(max_length=200, null=True, verbose_name='评论内容'),
        ),
    ]
