# Generated by Django 2.2.3 on 2019-08-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getinfo', '0002_everycomponent_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='everycomponent',
            name='comment_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='评论数'),
        ),
    ]
