# Generated by Django 2.2.3 on 2019-08-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getinfo', '0003_everycomponent_comment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everycomponent',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
    ]
