# Generated by Django 2.2.3 on 2019-08-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getinfo', '0004_auto_20190819_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='everycomponent',
            name='lesshome',
            field=models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='剩余房间数量'),
        ),
    ]
