# Generated by Django 2.2.3 on 2019-08-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getinfo', '0007_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
