# Generated by Django 2.2.3 on 2019-08-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getinfo', '0009_xiuxianyule'),
    ]

    operations = [
        migrations.AddField(
            model_name='xiuxianyule',
            name='type',
            field=models.CharField(max_length=10, null=True, verbose_name='类型'),
        ),
    ]
