# Generated by Django 2.2.3 on 2019-08-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getinfo', '0010_xiuxianyule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='xiuxianyule',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='城市名'),
        ),
    ]
