# Generated by Django 2.2.3 on 2019-08-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getinfo', '0011_xiuxianyule_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xiuxiannongjia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=50, verbose_name='店名')),
                ('pinfen', models.CharField(max_length=50, verbose_name='评分')),
                ('comment_amount', models.CharField(max_length=50, verbose_name='评分人数')),
                ('location', models.CharField(max_length=50, verbose_name='位置')),
                ('price', models.CharField(max_length=50, verbose_name='价格')),
            ],
        ),
    ]
