# Generated by Django 2.2.3 on 2019-08-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getinfo', '0013_xiuxiannongjia_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='xiuxiannongjia',
            name='images',
            field=models.CharField(max_length=500, null=True, verbose_name='图片'),
        ),
    ]
