# Generated by Django 2.2.3 on 2019-07-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('imgpath', models.CharField(blank=True, max_length=200, null=True, verbose_name='食物照片')),
                ('title', models.CharField(max_length=50, verbose_name='店家名')),
                ('star', models.CharField(blank=True, max_length=50, null=True, verbose_name='星级')),
                ('price', models.CharField(max_length=10, verbose_name='价格')),
                ('distance', models.CharField(max_length=50, verbose_name='距离')),
                ('labels', models.CharField(max_length=50, verbose_name='标签')),
                ('evaluate', models.CharField(max_length=50, verbose_name='奖项')),
                ('group', models.CharField(max_length=50, verbose_name='组队优惠信息')),
                ('coupons', models.CharField(max_length=50, verbose_name='优惠券信息')),
            ],
        ),
    ]
